export const cartTypes ={
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    ADD_ITEMS : 'ADD_ITEMS',
    REMOVE_ITEMS: 'REMOVE_ITEMS',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CLEAR_CHART : 'CLEAR_CHART'
    

}